package org.group2.entity;
// Generated Nov 14, 2013 6:33:44 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RegisteredType generated by hbm2java
 */
public class RegisteredType  implements java.io.Serializable {


     private int registeredTypeId;
     private String registeredTypeName;
     private Set<RegisteredUnit> registeredUnits = new HashSet<RegisteredUnit>(0);

    public RegisteredType() {
    }

	
    public RegisteredType(int registeredTypeId, String registeredTypeName) {
        this.registeredTypeId = registeredTypeId;
        this.registeredTypeName = registeredTypeName;
    }
    public RegisteredType(int registeredTypeId, String registeredTypeName, Set<RegisteredUnit> registeredUnits) {
       this.registeredTypeId = registeredTypeId;
       this.registeredTypeName = registeredTypeName;
       this.registeredUnits = registeredUnits;
    }
   
    public int getRegisteredTypeId() {
        return this.registeredTypeId;
    }
    
    public void setRegisteredTypeId(int registeredTypeId) {
        this.registeredTypeId = registeredTypeId;
    }
    public String getRegisteredTypeName() {
        return this.registeredTypeName;
    }
    
    public void setRegisteredTypeName(String registeredTypeName) {
        this.registeredTypeName = registeredTypeName;
    }
    public Set<RegisteredUnit> getRegisteredUnits() {
        return this.registeredUnits;
    }
    
    public void setRegisteredUnits(Set<RegisteredUnit> registeredUnits) {
        this.registeredUnits = registeredUnits;
    }




}


