package com.c1012l.radiocabs.entity;
// Generated Nov 12, 2013 4:44:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Billing generated by hbm2java
 */
public class Billing  implements java.io.Serializable {


     private int billingId;
     private PaymentType paymentType;
     private RegisteredUnit registeredUnit;
     private double money;
     private Date purchaseDate;
     private Date expriateDate;

    public Billing() {
    }

	
    public Billing(int billingId, PaymentType paymentType, RegisteredUnit registeredUnit, double money) {
        this.billingId = billingId;
        this.paymentType = paymentType;
        this.registeredUnit = registeredUnit;
        this.money = money;
    }
    public Billing(int billingId, PaymentType paymentType, RegisteredUnit registeredUnit, double money, Date purchaseDate, Date expriateDate) {
       this.billingId = billingId;
       this.paymentType = paymentType;
       this.registeredUnit = registeredUnit;
       this.money = money;
       this.purchaseDate = purchaseDate;
       this.expriateDate = expriateDate;
    }
   
    public int getBillingId() {
        return this.billingId;
    }
    
    public void setBillingId(int billingId) {
        this.billingId = billingId;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public RegisteredUnit getRegisteredUnit() {
        return this.registeredUnit;
    }
    
    public void setRegisteredUnit(RegisteredUnit registeredUnit) {
        this.registeredUnit = registeredUnit;
    }
    public double getMoney() {
        return this.money;
    }
    
    public void setMoney(double money) {
        this.money = money;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public Date getExpriateDate() {
        return this.expriateDate;
    }
    
    public void setExpriateDate(Date expriateDate) {
        this.expriateDate = expriateDate;
    }




}


