package com.c1012l.radiocabs.entity;
// Generated Nov 5, 2013 10:05:47 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedbackId;
     private FeedbackType feedbackType;
     private Serializable name;
     private String moblie;
     private String email;
     private Serializable ciry;
     private Serializable description;

    public Feedback() {
    }

	
    public Feedback(int feedbackId, FeedbackType feedbackType, Serializable name) {
        this.feedbackId = feedbackId;
        this.feedbackType = feedbackType;
        this.name = name;
    }
    public Feedback(int feedbackId, FeedbackType feedbackType, Serializable name, String moblie, String email, Serializable ciry, Serializable description) {
       this.feedbackId = feedbackId;
       this.feedbackType = feedbackType;
       this.name = name;
       this.moblie = moblie;
       this.email = email;
       this.ciry = ciry;
       this.description = description;
    }
   
    public int getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public FeedbackType getFeedbackType() {
        return this.feedbackType;
    }
    
    public void setFeedbackType(FeedbackType feedbackType) {
        this.feedbackType = feedbackType;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public String getMoblie() {
        return this.moblie;
    }
    
    public void setMoblie(String moblie) {
        this.moblie = moblie;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getCiry() {
        return this.ciry;
    }
    
    public void setCiry(Serializable ciry) {
        this.ciry = ciry;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }




}


