package com.c1012l.radiocabs.entity;
// Generated Nov 12, 2013 4:44:31 PM by Hibernate Tools 3.2.1.GA



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedbackId;
     private FeedbackType feedbackType;
     private String name;
     private String moblie;
     private String email;
     private String city;
     private String description;

    public Feedback() {
    }

	
    public Feedback(int feedbackId, FeedbackType feedbackType, String name) {
        this.feedbackId = feedbackId;
        this.feedbackType = feedbackType;
        this.name = name;
    }
    public Feedback(int feedbackId, FeedbackType feedbackType, String name, String moblie, String email, String city, String description) {
       this.feedbackId = feedbackId;
       this.feedbackType = feedbackType;
       this.name = name;
       this.moblie = moblie;
       this.email = email;
       this.city = city;
       this.description = description;
    }
   
    public int getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public FeedbackType getFeedbackType() {
        return this.feedbackType;
    }
    
    public void setFeedbackType(FeedbackType feedbackType) {
        this.feedbackType = feedbackType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMoblie() {
        return this.moblie;
    }
    
    public void setMoblie(String moblie) {
        this.moblie = moblie;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


