package com.c1012l.radiocabs.entity;
// Generated Nov 12, 2013 4:44:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentType generated by hbm2java
 */
public class PaymentType  implements java.io.Serializable {


     private int paymentTypeId;
     private String paymentTypeName;
     private Set billings = new HashSet(0);

    public PaymentType() {
    }

	
    public PaymentType(int paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }
    public PaymentType(int paymentTypeId, String paymentTypeName, Set billings) {
       this.paymentTypeId = paymentTypeId;
       this.paymentTypeName = paymentTypeName;
       this.billings = billings;
    }
   
    public int getPaymentTypeId() {
        return this.paymentTypeId;
    }
    
    public void setPaymentTypeId(int paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }
    public String getPaymentTypeName() {
        return this.paymentTypeName;
    }
    
    public void setPaymentTypeName(String paymentTypeName) {
        this.paymentTypeName = paymentTypeName;
    }
    public Set getBillings() {
        return this.billings;
    }
    
    public void setBillings(Set billings) {
        this.billings = billings;
    }




}


