package com.c1012l.radiocabs.entity;
// Generated Nov 5, 2013 10:05:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private PaymentType paymentType;
     private RegisteredUnit registeredUnit;
     private double money;
     private Date purchaseDate;
     private Date expriateDate;

    public Payment() {
    }

	
    public Payment(int paymentId, PaymentType paymentType, RegisteredUnit registeredUnit, double money) {
        this.paymentId = paymentId;
        this.paymentType = paymentType;
        this.registeredUnit = registeredUnit;
        this.money = money;
    }
    public Payment(int paymentId, PaymentType paymentType, RegisteredUnit registeredUnit, double money, Date purchaseDate, Date expriateDate) {
       this.paymentId = paymentId;
       this.paymentType = paymentType;
       this.registeredUnit = registeredUnit;
       this.money = money;
       this.purchaseDate = purchaseDate;
       this.expriateDate = expriateDate;
    }
   
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public RegisteredUnit getRegisteredUnit() {
        return this.registeredUnit;
    }
    
    public void setRegisteredUnit(RegisteredUnit registeredUnit) {
        this.registeredUnit = registeredUnit;
    }
    public double getMoney() {
        return this.money;
    }
    
    public void setMoney(double money) {
        this.money = money;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public Date getExpriateDate() {
        return this.expriateDate;
    }
    
    public void setExpriateDate(Date expriateDate) {
        this.expriateDate = expriateDate;
    }




}


