package com.c1012l.radiocabs.entity;
// Generated Nov 7, 2013 1:20:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * RegisteredType generated by hbm2java
 */
public class RegisteredType  implements java.io.Serializable {


     private int registeredTypeId;
     private Serializable registeredTypeName;
     private Set<RegisteredUnit> registeredUnits = new HashSet<RegisteredUnit>(0);

    public RegisteredType() {
    }

	
    public RegisteredType(int registeredTypeId, Serializable registeredTypeName) {
        this.registeredTypeId = registeredTypeId;
        this.registeredTypeName = registeredTypeName;
    }
    public RegisteredType(int registeredTypeId, Serializable registeredTypeName, Set<RegisteredUnit> registeredUnits) {
       this.registeredTypeId = registeredTypeId;
       this.registeredTypeName = registeredTypeName;
       this.registeredUnits = registeredUnits;
    }
   
    public int getRegisteredTypeId() {
        return this.registeredTypeId;
    }
    
    public void setRegisteredTypeId(int registeredTypeId) {
        this.registeredTypeId = registeredTypeId;
    }
    public Serializable getRegisteredTypeName() {
        return this.registeredTypeName;
    }
    
    public void setRegisteredTypeName(Serializable registeredTypeName) {
        this.registeredTypeName = registeredTypeName;
    }
    public Set<RegisteredUnit> getRegisteredUnits() {
        return this.registeredUnits;
    }
    
    public void setRegisteredUnits(Set<RegisteredUnit> registeredUnits) {
        this.registeredUnits = registeredUnits;
    }




}


