package com.c1012l.radiocabs.entity;
// Generated Nov 12, 2013 4:44:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RegisteredType generated by hbm2java
 */
public class RegisteredType  implements java.io.Serializable {


     private int registeredTypeId;
     private String registeredTypeName;
     private Set registeredUnits = new HashSet(0);

    public RegisteredType() {
    }

	
    public RegisteredType(int registeredTypeId, String registeredTypeName) {
        this.registeredTypeId = registeredTypeId;
        this.registeredTypeName = registeredTypeName;
    }
    public RegisteredType(int registeredTypeId, String registeredTypeName, Set registeredUnits) {
       this.registeredTypeId = registeredTypeId;
       this.registeredTypeName = registeredTypeName;
       this.registeredUnits = registeredUnits;
    }
   
    public int getRegisteredTypeId() {
        return this.registeredTypeId;
    }
    
    public void setRegisteredTypeId(int registeredTypeId) {
        this.registeredTypeId = registeredTypeId;
    }
    public String getRegisteredTypeName() {
        return this.registeredTypeName;
    }
    
    public void setRegisteredTypeName(String registeredTypeName) {
        this.registeredTypeName = registeredTypeName;
    }
    public Set getRegisteredUnits() {
        return this.registeredUnits;
    }
    
    public void setRegisteredUnits(Set registeredUnits) {
        this.registeredUnits = registeredUnits;
    }




}


