package com.c1012l.radiocabs.entity;
// Generated Nov 7, 2013 1:20:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * RegisteredUnit generated by hbm2java
 */
public class RegisteredUnit  implements java.io.Serializable {


     private String registrationId;
     private RegisteredType registeredType;
     private Serializable name;
     private String password;
     private Serializable contactPerson;
     private Serializable designation;
     private String faxNumber;
     private Integer membershipType;
     private Serializable city;
     private Integer experience;
     private Serializable description;
     private Serializable address;
     private String mobile;
     private String telephone;
     private String email;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public RegisteredUnit() {
    }

	
    public RegisteredUnit(String registrationId, Serializable name, String password) {
        this.registrationId = registrationId;
        this.name = name;
        this.password = password;
    }
    public RegisteredUnit(String registrationId, RegisteredType registeredType, Serializable name, String password, Serializable contactPerson, Serializable designation, String faxNumber, Integer membershipType, Serializable city, Integer experience, Serializable description, Serializable address, String mobile, String telephone, String email, Set<Payment> payments) {
       this.registrationId = registrationId;
       this.registeredType = registeredType;
       this.name = name;
       this.password = password;
       this.contactPerson = contactPerson;
       this.designation = designation;
       this.faxNumber = faxNumber;
       this.membershipType = membershipType;
       this.city = city;
       this.experience = experience;
       this.description = description;
       this.address = address;
       this.mobile = mobile;
       this.telephone = telephone;
       this.email = email;
       this.payments = payments;
    }
   
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public RegisteredType getRegisteredType() {
        return this.registeredType;
    }
    
    public void setRegisteredType(RegisteredType registeredType) {
        this.registeredType = registeredType;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Serializable getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(Serializable contactPerson) {
        this.contactPerson = contactPerson;
    }
    public Serializable getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(Serializable designation) {
        this.designation = designation;
    }
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }
    public Integer getMembershipType() {
        return this.membershipType;
    }
    
    public void setMembershipType(Integer membershipType) {
        this.membershipType = membershipType;
    }
    public Serializable getCity() {
        return this.city;
    }
    
    public void setCity(Serializable city) {
        this.city = city;
    }
    public Integer getExperience() {
        return this.experience;
    }
    
    public void setExperience(Integer experience) {
        this.experience = experience;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


